
[log]
filename="./logs/gobog.log" #log file name
level=7                     #log level
maxlines=0                  #max lines per file
maxsize=0                   #max size per file
daily=true                  #daily rotate
maxdays=10                  #how many days saved log file
color=true                  #color

[http]
cert="./cert/1_www.sbrave.cn_bundle.crt"
key="./cert/2_www.sbrave.cn.key"
# listen 80 address needs root permission
addr=["80"]
addrs=["443"]

[blog]
domain="https://sbrave.cn"
title="smart的个人博客"
subtitle="代码分享专栏"
description="阅读·实践·分享"
--description="Stay hungry,stay foolish."
author="smart"
theme="themes/simple"
source="_source"

[mysql]
user="user"
passwd=""
db="blog"
