
[log]
formatStr="%{color}%{time:15:04:05.000} %{shortfunc} ▶ %{level:.4s} %{id:03x}%{color:reset} %{message}"
path="./logs/gobog.log"

[http]
addr="10000"

[blog]
title="smart的个人博客"
subtitle="代码分享专栏"
description="阅读·实践·分享"
--description="Stay hungry,stay foolish."
author="smart"
theme="simple"
csspath="./themes/simple/css"
jspath="./themes/simple/js"
domain="https://www.sbrave.cn"
postpath="./_source/post"
aboutpath="./_source/about"
imagepath="./_source/image"
videopath="./_source/video"
audiopath="./_source/audio"

[mysql]
user="user"
passwd=""
db="blog"
